### ISSUE TITLE
Figure out how to handle NA cells

### ISSUE THREAD

**Issue by dunn-cwu** [dunn-cwu/CS567_Project_2#4]

**Comment by dunn-cwu** [comment]
Some ideas: https://medium.com/coinmonks/dealing-with-missing-data-using-r-3ae428da2d17

Or just delete the entire rows

**Comment by paulcollet** [comment]
The na.rm seems to be the recommended function to use, but it's implemented as something is calling the data:
    data <- sapply(data, as.numeric, na.rm=TRUE)
The problem is the step function doesn't like missing values:
    https://stat.ethz.ch/R-manual/R-devel/library/stats/html/step.html (see values)
So far, I get the following error regardless where I implement it:
    AIC is -infinity for this model, so 'step' cannot proceed

**Comment by paulcollet** [comment]
> 
> 
> Some ideas: https://medium.com/coinmonks/dealing-with-missing-data-using-r-3ae428da2d17
> 
> Or just delete the entire rows

I tried that: it only leaves us with two rows of data.

**Comment by paulcollet** [comment]
Done
