### ISSUE TITLE
Complete forward elimination and/or stepwise (forward-backward)

### ISSUE THREAD

**Issue by dunn-cwu** [dunn-cwu/CS567_Project_2#5]

**Comment by paulcollet** [comment]
This seems to work:
step(FitAll, direction = c("both", "backward", "forward"))
Maybe just "both?" It's hard to figure out what the results are in the mountain of text that it gives you.

**Comment by safrannn** [comment]
train.R pushed for k-fold cross validation(because we don't have much data so this might be a good try).
forward, backward and stepwise selection can be easily changed, code for all three is in the file.
Currently waiting for the data to decide on the column to predict.

**Comment by reevesba** [comment]
I was able to use backward and forwards elimination successfully, but the model is still weak. I think it's going to come down to how we manipulate and transform the data. Also, k-fold cross validation is a great idea Su. I will definitely be testing that.
