### ISSUE TITLE
packages & slight Issue 

### ISSUE THREAD

**Issue by paulcollet** [dunn-cwu/CS567_Project_2#7]
I added the styler library because we talked about using Tiddyverse. However, unless we take the time to learn how to initialize/apply it, it's not doing anything. I don't think our code is going to be long enough to warrant the effort.

**Comment by safrannn** [comment]
if anyone has problem installing packages below is the code
install.packages("stringr", dependencies=TRUE, INSTALL_opts = c('--no-lock'))
install.packages("standardize", dependencies=TRUE, INSTALL_opts = c('--no-lock'))

**Comment by reevesba** [comment]
I agree Paul. I did notice that there is a package there to clean all scripts in a directory automatically. I will look into this and create a script for it if there is time.
